accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailArticleView, AccountUpdateView, AccountDeleteView, \
    AccountDetailProjectView, AccountDetailView

app_name = 'accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail_article/<int:pk>', AccountDetailArticleView.as_view(), name='detail_article'),
    path('detail_project/<int:pk>', AccountDetailProjectView.as_view(), name='detail_project'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.


class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld
from articleapp.models import Article
from projectapp.models import Project

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

class AccountDetailArticleView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail_article.html'

    paginate_by = 20

    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(writer=self.object)
        # project_list = Project.objects.filter(writer=self.object)
        # print(vars(article_list))
        # print(vars(project_list))
        return super().get_context_data(object_list=article_list, object_name='article', **kwargs)

class AccountDetailProjectView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail_project.html'

    paginate_by = 20

    def get_context_data(self, **kwargs):
        # article_list = Article.objects.filter(writer=self.object)
        project_list = Project.objects.filter(writer=self.object)
        # print(vars(article_list))
        # print(vars(project_list))
        return super().get_context_data(object_list=project_list, object_name='project',**kwargs)




has_ownership = [login_required, account_ownership_required]


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail_article', kwargs={'pk': self.object.pk})


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}


    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>
                Signs Up
            </h4>
        </div>
        <div>
            <form action="{% url 'accountapp:create' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}


    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>
                Quit
            </h4>
        </div>
        <div>
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-danger rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="text-center mw-500 m-auto">
            <span class="mx-100">
                <span class="mx-3">
                    <a class="material-icons" href="{% url 'accountapp:detail_article' pk=user.pk %}">
                        menu_book

                    </a>
                    <span stlye="font-size:1rem">
                        <a href="{% url 'accountapp:detail_article' pk=user.pk %}">나의여행기</a>
                    </span>
                </span>
                <span class="mx-3">
                    <a class="material-icons">
                        library_books
                    </a>
                    <span stlye="size:1rem">
                        <a href="{% url 'accountapp:detail_project' pk=user.pk %}">나의다이어리</a>
                    </span>
                </span>

            </span>
            <span class="mx-100">

            </span>
        </div>

    {% endif %}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}"
                     class="profile_image m-4"
                     alt="profile image">
                <h2 class="NNS_B">
                    {{ target_user.profile.nickname }}
                        {% if target_user == user %}
                            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                               class="material-icons round_button">
                                edit
                            </a>
                        {% endif %}
                </h2>
                <h5>{{ target_user.profile.message }}</h5>
            {% else %}
            <h2>
                <a href="{% url 'profileapp:create' %}">
                    Create Profile
                </a>
            </h2>
            {% endif %}
        </div>

        {% if user == target_user %}
        <div>
            <a href="{% url 'accountapp:update' pk=target_user.pk %}"
               class="material-icons round_button mx-1">
                settings
            </a>
            <a href="{% url 'accountapp:delete' pk=target_user.pk %}"
               class="material-icons round_button mx-1">
                close
            </a>
        </div>
        {% endif %}
    </div>

{% endblock %}

accountapp/templates/accountapp/detail_article.html
{% extends 'base.html' %}

{% block content %}


    {% if user.is_authenticated %}
        <div class="text-center mw-500 m-auto">
            <span class="mx-100">
                <span class="mx-3">
                    <a class="material-icons" href="{% url 'accountapp:detail_article' pk=user.pk %}">
                        menu_book

                    </a>
                    <span stlye="font-size:1rem">
                        <a href="{% url 'accountapp:detail_article' pk=user.pk %}">나의여행기</a>
                    </span>
                </span>
                <span class="mx-3">
                    <a class="material-icons">
                        library_books
                    </a>
                    <span stlye="size:1rem">
                        <a href="{% url 'accountapp:detail_project' pk=user.pk %}">나의다이어리</a>
                    </span>
                </span>

            </span>
            <span class="mx-100">

            </span>
        </div>

    {% endif %}

    <div>
        {% include 'snippets/list_fragment.html' with object_list=object_list %}
    </div>


{% endblock %}

accountapp/templates/accountapp/detail_project.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="text-center mw-500 m-auto">
            <span class="mx-100">
                <span class="mx-3">
                    <a class="material-icons" href="{% url 'accountapp:detail_article' pk=user.pk %}">
                        menu_book

                    </a>
                    <span stlye="font-size:1rem">
                        <a href="{% url 'accountapp:detail_article' pk=user.pk %}">나의여행기</a>
                    </span>
                </span>
                <span class="mx-3">
                    <a class="material-icons">
                        library_books
                    </a>
                    <span stlye="size:1rem">
                        <a href="{% url 'accountapp:detail_project' pk=user.pk %}">나의다이어리</a>
                    </span>
                </span>

            </span>
            <span class="mx-100">

            </span>
        </div>

    {% endif %}

    <div>
        {% include 'snippets/list_fragment.html' with object_list=object_list %}
    </div>


{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>
                Login
            </h4>
        </div>
        <div>
            <form action="{% url 'accountapp:login' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}


    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>
                Update Info
            </h4>
        </div>
        <div>
            <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %}