articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView, ProjectUpdateView, ProjectDeleteView, ProjectCollectionView

app_name='projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
    path('updata/<int:pk>', ProjectUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ProjectDeleteView.as_view(), name='delete'),
    path('collection/<int:pk>', ProjectCollectionView.as_view(), name='collection'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/<int:project_pk>', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

projectapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=20, null=False)
    description = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='project/', null=False)
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,
                               related_name='project', null=True)
    created_at = models.DateField(auto_now_add=True, null=True)
    is_private = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.title}'

projectapp/forms.py
from django.forms import ModelForm
from django import forms
from projectapp.models import Project


class ProjectCreationForm(ModelForm):
    is_private = forms.BooleanField(required=False)
    class Meta:
        model = Project
        fields = ['title','image','description','is_private']

projectapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.views.generic.edit import FormMixin, DeleteView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from projectapp.decorators import project_ownership_required
from projectapp.forms import ProjectCreationForm
from projectapp.models import Project
from subscribeapp.models import Subscription


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    # success_url = reverse_lazy('articleapp:list') login_required를 적용하였으므로 아래의와 같이 get_success_url 메소드를 재정의한다.
    template_name = 'projectapp/create.html'
    def form_valid(self, form):
        form.instance.writer = self.request.user #request를 보내는 user로 writer를 할당
        return super().form_valid(form)
    def get_success_url(self):
        return reverse("projectapp:detail" , kwargs={"pk":self.object.pk})


class ProjectDetailView(DetailView, MultipleObjectMixin):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'

    paginate_by = 20

    def get_context_data(self, **kwargs):
        user = self.request.user
        project = self.object

        if user.is_authenticated:
            subscription = Subscription.objects.filter(user=user,
                                                       project=project)
        else:
            subscription = None

        article_list = Article.objects.filter(project=self.object)
        lat_lon = article_list.values('lat','lon')
        return super().get_context_data(object_list=article_list,
                                        subscription=subscription, lat_lon=lat_lon ,object_name='article',
                                        **kwargs)

from django.db.models import Avg, Min, Max, Count, F, Sum
class ProjectCollectionView(DetailView):
    model = Project
    context_object_name = 'project_list'
    template_name = 'projectapp/collection.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(project=self.object)
        lat_lon = article_list.values('lat','lon')
        print(lat_lon)
        lat = Article.objects.aggregate(Avg('lat'))
        lon = Article.objects.aggregate(Avg('lon'))
        return super().get_context_data(article_list=article_list,lat_lon=lat_lon,lat=lat,lon=lon,**kwargs)


class ProjectListView(ListView):
    model = Project
    context_object_name = 'project_list'
    template_name = 'projectapp/list.html'
    paginate_by = 20

@method_decorator(project_ownership_required,'get')
@method_decorator(project_ownership_required,'post')
class ProjectUpdateView(UpdateView):
    model = Project
    form_class = ProjectCreationForm
    context_object_name = 'target_project'
    template_name = 'projectapp/update.html'
    def get_success_url(self):
        return reverse('projectapp/detail_article.html', kwargs={'pk':self.object.pk})

@method_decorator(project_ownership_required,'get')
@method_decorator(project_ownership_required,'post')
class ProjectDeleteView(DeleteView):
    model = Project
    context_object_name = 'target_project'
    success_url = reverse_lazy('projectapp:list')
    template_name = 'projectapp/delete.html'

projectapp/templates/projectapp/collection.html
{% extends 'base.html' %}
<style>
    .map_wrap, .map_wrap * {margin:0;padding:0;font-family:'Malgun Gothic',dotum,'돋움',sans-serif;font-size:12px;}
    .map_wrap a, .map_wrap a:hover, .map_wrap a:active{color:#000;text-decoration: none;}
    .map_wrap {position:relative;width:50%;height:500px;}
    #menu_wrap {position:absolute;top:0;left:0;bottom:0;width:250px;margin:10px 0 30px 10px;padding:5px;overflow-y:auto;background:rgba(255, 255, 255, 0.7);z-index: 1;font-size:12px;border-radius: 10px;}
    .bg_white {background:#fff;}
    #menu_wrap hr {display: block; height: 1px;border: 0; border-top: 2px solid #5F5F5F;margin:3px 0;}
    #menu_wrap .option{text-align: center;}
    #menu_wrap .option p {margin:10px 0;}
    #menu_wrap .option button {margin-left:5px;}
    #placesList li {list-style: none;}
    #placesList .item {position:relative;border-bottom:1px solid #888;overflow: hidden;cursor: pointer;min-height: 65px;}
    #placesList .item span {display: block;margin-top:4px;}
    #placesList .item h5, #placesList .item .info {text-overflow: ellipsis;overflow: hidden;white-space: nowrap;}
    #placesList .item .info{padding:10px 0 10px 55px;}
    #placesList .info .gray {color:#8a8a8a;}
    #placesList .info .jibun {padding-left:26px;background:url(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/places_jibun.png) no-repeat;}
    #placesList .info .tel {color:#009900;}
    #placesList .item .markerbg {float:left;position:absolute;width:36px; height:37px;margin:10px 0 0 10px;background:url(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png) no-repeat;}
    #placesList .item .marker_1 {background-position: 0 -10px;}
    #placesList .item .marker_2 {background-position: 0 -56px;}
    #placesList .item .marker_3 {background-position: 0 -102px}
    #placesList .item .marker_4 {background-position: 0 -148px;}
    #placesList .item .marker_5 {background-position: 0 -194px;}
    #placesList .item .marker_6 {background-position: 0 -240px;}
    #placesList .item .marker_7 {background-position: 0 -286px;}
    #placesList .item .marker_8 {background-position: 0 -332px;}
    #placesList .item .marker_9 {background-position: 0 -378px;}
    #placesList .item .marker_10 {background-position: 0 -423px;}
    #placesList .item .marker_11 {background-position: 0 -470px;}
    #placesList .item .marker_12 {background-position: 0 -516px;}
    #placesList .item .marker_13 {background-position: 0 -562px;}
    #placesList .item .marker_14 {background-position: 0 -608px;}
    #placesList .item .marker_15 {background-position: 0 -654px;}
    #pagination {margin:10px auto;text-align: center;}
    #pagination a {display:inline-block;margin-right:10px;}
    #pagination .on {font-weight: bold; cursor: default;color:#777;}
</style>

{% block content %}
    <div id="map" style="width:100%;height:350px;"></div>
    {% for target_article in article_list %}

    <div class="container text-center">
        <div class="my-3">
            {#      제목, 장소, 글쓴이, 작성일자      #}
            <h1 class="NNS_B" style="font-size: 3rem">{{ target_article.title }}</h1>
            <div class="my-2">
                <a href="{% url 'likeapp:article_like' article_pk=target_article.pk %}" class="material-icons"
                style="vertical-align: middle; font-size:1.4rem; color: #f88;">
                    favorite
                </a>
                <span style="vertical-align: middle; font-size:1.1rem; ">
                    {{ target_article.like }}
                </span>
             </div>
            {# Like App : 좋아요 기능 이식 END #}
            <h3>{{ target_article.writer.profile.nickname }}</h3>
            <p>{{ target_article.created_at }}</p>
            <div>
                <p>비공개여부: {{ target_article.is_private }}</p>
            </div>
                <div>
                    <p style="margin: 0.2rem; display: inline;">기쁨 : {{ target_article.joy }}</p>
                    <p style="margin: 0.2rem; display: inline;">슬픔 : {{ target_article.sadness }}</p>
                    <p style="margin: 0.2rem; display: inline;">불안 : {{ target_article.fear }}</p>
                </div>
                <div>
                    <p style="margin: 0.2rem; display: inline;">당황 : {{ target_article.upset }}</p>
                    <p style="margin: 0.2rem; display: inline;">분노 : {{ target_article.anger }}</p>
                    <p style="margin: 0.2rem; display: inline;">상처 : {{ target_article.hurt }}</p>
                </div>
        </div>
        <h3 class="NNS_B">{{ target_article.place }}</h3>

        <div id="map{{forloop.counter}}" style="width:100%;height:350px;"></div>


        <div class="my-4">
            {#      게시글 대표 이미지, 게시글 내용      #}
            <img src="{{ target_article.image.url }}"
                 class="article_image"
                 alt="">
            <div class="article_content my-5">
                {{ target_article.content | safe}}
                {#  html 태그들을 안전하게 반영시켜주는 역할을 함 : safe #}
            </div>
            {% if target_article.writer == user %}
{#            <div>#}
{#                <a href="{% url 'articleapp:update' pk=target_article.pk %}"#}
{#                   class="btn btn-success rounded-pill px-5">#}
{#                    Update#}
{#                </a>#}
{#                <a href="{% url 'articleapp:delete' pk=target_article.pk %}"#}
{#                   class="btn btn-danger rounded-pill px-5">#}
{#                    Delete#}
{#                </a>#}
{#            </div>#}
            {% endif %}
        </div>
        <hr>
    </div>
    {% endfor %}

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=7a0506c93dc9967fe1cbf31894fab580&libraries=services,clusterer,drawing"></script>
    <script>

    var mapContainer = document.getElementById('map'), // 지도를 표시할 div
            mapOption = {
                center: new kakao.maps.LatLng({{ lat.lat__avg }}, {{ lon.lon__avg }}), // 지도의 중심좌표
                level: 6 // 지도의 확대 레벨
            };

    // 지도를 생성합니다
    var map_main = new kakao.maps.Map(mapContainer, mapOption);
{% for data in lat_lon %}

    var mapContainer = document.getElementById('map{{forloop.counter}}'), // 지도를 표시할 div
    mapOption = {
        center: new kakao.maps.LatLng({{ data.lat }}, {{ data.lon }}), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨
    };

    // 지도를 생성합니다
    var map = new kakao.maps.Map(mapContainer, mapOption);

    // 주소-좌표 변환 객체를 생성합니다
    var geocoder = new kakao.maps.services.Geocoder();
    map.setCenter(new kakao.maps.LatLng({{ data.lat }}, {{ data.lon }}));

    // 지도를 클릭한 위치에 표출할 마커입니다
    var marker = new kakao.maps.Marker({
        // 지도 중심좌표에 마커를 생성합니다
        position: map.getCenter()
    });
    // 지도에 마커를 표시합니다
    marker.setMap(map);



    // 마커가 표시될 위치입니다
    var markerPosition  = new kakao.maps.LatLng({{ data.lat }}, {{ data.lon }});

    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({
        position: markerPosition
    });

    // 마커가 지도 위에 표시되도록 설정합니다
    marker.setMap(map_main);


{% endfor %}

</script>

{% endblock %}

projectapp/templates/projectapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static 'beagle.css' %}">

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>
                Create Project
            </h4>
        </div>
        <div>
            <form action="{% url 'projectapp:create' %}"
                  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

projectapp/templates/projectapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
           <h4>
               Delete Project : {{ target_project.title }}
           </h4>
        </div>
        <div>
            <form action="{% url 'projectapp:delete' pk=target_project.pk %}"
                  method="post">
                {% csrf_token %} <!--사이트간 해킹방지 우회-->
                <div class="m-5">
                <input type="submit"
                       class="btn btn-danger rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

projectapp/templates/projectapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div id="map" style="width:100%;height:600px; transform: scale(0.9,0.9);"></div>
    <div class="text-center mw-500 m-auto">

        <div class="m-5">
                <img src="{{ target_project.image.url }}"
                     class="profile_image m-4"
                     alt="profile image">
                <h2 class="NNS_B">
                    {{ target_project.name }}
                </h2>
                <a href="https://www.youtube.com/results?search_query={{ target_project.title }} 음악" target="_blank">{{ target_project.description }}</a>
        </div>

        <div>
            <a href="{% url 'projectapp:update' pk=target_project.pk %}"
               class="btn btn-success rounded-pill px-5">
                Update
            </a>
            <a href="{% url 'projectapp:delete' pk=target_project.pk %}"
               class="btn btn-danger rounded-pill px-5">
                Delete
            </a>

            <a href="{% url 'projectapp:collection' pk=target_project.pk %}"
               class="btn btn-warning rounded-pill px-5 my-2">
                Diary Collection
            </a>
        </div>

    </div>

    {% if user.is_authenticated %}
    <div class="text-center">
        {% if not subscription %}
        <a href="{% url 'subscribeapp:subscribe' project_pk=target_project.pk %}"
           class="btn btn-primary rounded-pill px-5">
            Subscribe
        </a>
        {% else %}
        <a href="{% url 'subscribeapp:subscribe' project_pk=target_project.pk %}"
           class="btn btn-secondary rounded-pill px-5">
            Unsubscribe
        </a>
        {% endif %}
    </div>
    {% endif %}

    <div>
        {% include 'snippets/list_fragment.html' with object_list=object_list %}
    </div>



    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=7a0506c93dc9967fe1cbf31894fab580&libraries=services"></script>
    <script>
    var mapContainer = document.getElementById('map{{forloop.counter}}'), // 지도를 표시할 div
            mapOption = {
                center: new kakao.maps.LatLng(35, 127), // 지도의 중심좌표
                level: 3 // 지도의 확대 레벨
            };

    // 지도를 생성합니다
    var map = new kakao.maps.Map(mapContainer, mapOption);

    {% for data in lat_lon %}
        console.log({{ data.lat }})


        // 주소-좌표 변환 객체를 생성합니다
        var geocoder = new kakao.maps.services.Geocoder();
        map.setCenter(new kakao.maps.LatLng({{ data.lat }}, {{ data.lon }}));

        // 지도를 클릭한 위치에 표출할 마커입니다
        var marker = new kakao.maps.Marker({
            // 지도 중심좌표에 마커를 생성합니다
            position: map.getCenter()
        });
        // 지도에 마커를 표시합니다
        marker.setMap(map);

    {% endfor %}

    </script>

{% endblock %}

projectapp/templates/projectapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>
        .container{
            padding: 0;
            margin: 0 auto;
        }

        .container div {
            width: 45%;
            max-width: 100px;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 2rem;
            flex-direction: column;
            box-shadow: 0 0 .5rem darkgray;
        }

        .container img {
            width: 100%;
            border-radius: 2rem;
        }

    </style>

    <div class="container my-4">

        {% for project in project_list %}

            <div style="margin: 1.3rem;">
                <a href="{% url 'projectapp:detail' pk=project.pk %}">
                    <img src="{{ project.image.url }}" alt="">
                </a>
                <span class="NNS_B m-1">{{ project.title | truncatechars:7 }}</span>
            </div>

        {% endfor %}

    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>

    {% include 'snippets/pagination.html' %}

    <div class="text-center">
        <a href="{% url 'projectapp:create' %}"
           class="btn btn-outline-dark rounded-pill px-5 my-3">
            Create Project
        </a>
    </div>


{% endblock %}

projectapp/templates/projectapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static 'beagle.css' %}">
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
           <h4>
               Update Project
           </h4>
        </div>
        <div>
            <form action="{% url 'projectapp:update' pk=target_project.pk %}"
                  method="post" enctype="multipart/form-data">
                {% csrf_token %} <!--사이트간 해킹방지 우회-->
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>
    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}