accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailArticleView, AccountUpdateView, AccountDeleteView, \
    AccountDetailProjectView, AccountDetailView

app_name = 'accountapp'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail_article/<int:pk>', AccountDetailArticleView.as_view(), name='detail_article'),
    path('detail_project/<int:pk>', AccountDetailProjectView.as_view(), name='detail_project'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

emotionapp/urls.py
from django.urls import path

from emotionapp.views import EmotionCreateView, EmotionListView, EmotionUpdateView, EmotionDeleteView, EmotionDetailView

app_name='emotionapp'

urlpatterns = [
    path('create/', EmotionCreateView.as_view(), name='create'),
    path('list/', EmotionListView.as_view(), name='list'),
    path('detail/<int:pk>', EmotionDetailView.as_view(), name='detail'),
    path('updata/<int:pk>', EmotionUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', EmotionDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView, ProjectUpdateView, ProjectDeleteView, ProjectCollectionView

app_name='projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
    path('updata/<int:pk>', ProjectUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ProjectDeleteView.as_view(), name='delete'),
    path('collection/<int:pk>', ProjectCollectionView.as_view(), name='collection'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body>

{% include 'header.html' %}

{% for message in messages %}
    <div class="text-center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5">
            {{ message }}
        </div>
    </div>
{% endfor %}

<div class="div_border" style="padding-bottom: 5px;">
{% block content %}

{% endblock %}
</div>
{% include 'footer.html' %}
<div style="padding: 25px;"></div>

</body>
</html>

templates/footer.html
<style>
    .bottom_menu { position: fixed; bottom: 0px; left: 0px; width: 100%; height: 50px; z-index:100; border-top: 1px solid black; background-color: white }
    .bottom_menu > a { float: left; width:20%; height: 100%; text-align: center; padding-top: 13px; }
</style>

<div style="text-align: center">
    <div style="text-align: center">
    <div class="bottom_menu">
		 <a class="material-icons" href="{% url 'articleapp:list' %}">
            home
        </a>
        <a class="material-icons" href="{% url 'projectapp:list' %}">
            auto_stories
        </a>
        <a class="material-icons" href="{% url 'emotionapp:list' %}">
            sentiment_satisfied
        </a>
        <a class="material-icons" href="{% url 'subscribeapp:list' %}">
        bookmark
        </a>
        {% if user.is_authenticated %}
        <a class="material-icons" href="{% url 'accountapp:detail' pk=user.pk %}">
            person
        </a>
        {% endif %}
        {% if not user.is_authenticated %}
        <a class="material-icons" href="{% url 'accountapp:create' %}">
            person_add_alt_1
        </a>
        {% endif %}
	</div>
    <script>

    </script>
</div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Title</title>

    {#  BOOTSTRAP LINK  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {#  GOOGLE FONTS LINK  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=East+Sea+Dokdo&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap" rel="stylesheet">

    {#  STATIC FILES LINK  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {#  MATERIAL ICONS LINK  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'BMEuljiro10yearslater';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-10-21@1.0/BMEuljiro10yearslater.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }
    </style>

</head>

templates/header.html
<div class="div_border">
    <div class="pragmatic_header_logo">
        <h1 class="title_font">
            <a href="{% url 'home' %}">
                뮤직나우
            </a>
        </h1>
    </div>

{#    <div class="pragmatic_header_logo">#}
{#        <h1 style="display: inline-block; font-size: 3rem;">#}
{#            <a href="{% url 'home' %}">#}
{#                감성여행기#}
{#            </a>#}
{#        </h1>#}
{#    </div>#}


    {% if not user.is_authenticated %}
        <div style="position:relative; left: 1rem">
            <a href="{% url 'accountapp:login' %}" class="hover_white">
                로그인
            </a>

            <a href="{% url 'accountapp:create' %}" class="hover_white">
                회원가입
            </a>
        </div>
    {% else %}
            <a href="{% url 'articleapp:create' %}" class="hover_white">
        뮤직나우 작성
        </a>

        <a href="{% url 'accountapp:logout' %}" class="hover_white">
            로그아웃
        </a>

    {% endif %}



    <div class="header-font">
        <span class="mx-2">
                <a href="{% url 'recommendapp:main_html' %}">
                뮤직추천
            </a>
        </span>
        <span class="mx-2">
                <a href="{% url 'articleapp:list' %}">
                뮤직나우
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'projectapp:list' %}">
                뮤직다이어리
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'emotionapp:list' %}">
                우리의감성
            </a>
        </span>

        {% if user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'subscribeapp:list' %}">
                구독목록
            </a>
        </span>
        {% endif %}

    </div>
</div>