articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentDeleteView

app_name = 'commentapp'

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    # User가 탈퇴했을 경우, 작성자 미상(게시글에서) 처럼 되게 한다.
    # OneToOne과 다른 점은 다대다도 가능하다.
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='article/',null=True)
    # image = ProcessedImageField(
    #     upload_to='article/',  # 저장 위치
    #     processors=[ResizeToFill(600, 600)],  # 처리할 작업 목록
    #     format='JPEG',  # 저장 포맷(확장자)
    #     options={'quality': 90},  # 저장 포맷 관련 옵션 (JPEG 압축률 설정)
    # )
    content = models.TextField(null=True)
    created_at = models.DateField(auto_now_add=True, null=True)

    # 어떤 게시글이 연길되어 있는지 설정
    # 게시글과 프로젝트의 연결고리
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True, blank=True)

    # likeapp 과 연결된 칼럼
    like = models.IntegerField(default=0)  # 새로운 글을 썼을 때, default 0 으로 자동 저장됨.

    # emotion : sadness, anger, love, surprise, fear, joy
    # 기쁨 0 joy
    #
    # 슬픔 1 sadness
    #
    # 불안 2 fear
    #
    # 당황 3 upset
    #
    # 분노 4 anger
    #
    # 상처 5 hurt
    # joy, sadness, fear, upset, anger, hurt
    # 기쁨, 슬픔, 불안, 당항, 분노, 상처
    joy = models.FloatField(null=True)
    sadness = models.FloatField(null=True)
    fear = models.FloatField(null=True)
    upset = models.FloatField(null=True)
    anger = models.FloatField(null=True)
    hurt = models.FloatField(null=True)

    # 위도, 경도
    lat = models.FloatField(null=False)
    lon = models.FloatField(null=False)

    # 장소
    place = models.CharField(max_length=100, null=True)

    # 공개, 비공개
    is_private = models.BooleanField(default=False, null=False)

articleapp/forms.py
from django import forms
from django.forms import ModelForm

from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable',
                                                           'style': 'min-height: 10rem;'
                                                                    'text-align: left;'}))
    lat = forms.FloatField(widget=forms.HiddenInput())
    lon = forms.FloatField(widget=forms.HiddenInput())
    is_private = forms.BooleanField(required=False)
    class Meta:
        model = Article
        fields = ['title', 'image', 'project', 'place', 'content','lat','lon', 'is_private']

articleapp/views.py
import json

from django.contrib.auth.decorators import login_required

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm
import requests
import re

URL = 'http://15.164.232.127:5001/lyrics_emotion'
headers = {'User-Agent':'Mozila/5.0'}

@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    # success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        form.instance.writer = self.request.user  # Foreign Key 지정하여 삽입하기 위한 코드
        return super().form_valid(form)

    def get_success_url(self):  # self.object는 target_object와 동일하다고 보면 됨
        obj = Article.objects.get(pk=self.object.id)
        session = requests.Session()
        payload = {'lyrics' : obj.content}
        session = requests.Session()
        res = session.post(URL, headers=headers, data=payload)
        result = json.loads(res.text)['emotion_score']
        result_dict = {'joy':result[0], 'sadness':result[1], 'fear':result[2], 'upset':result[3], 'anger':result[4], 'hurt':result[5]}

        obj.joy = result_dict['joy']
        obj.sadness = result_dict['sadness']
        obj.fear = result_dict['fear']
        obj.upset = result_dict['upset']
        obj.anger = result_dict['anger']
        obj.hurt = result_dict['hurt']

        obj.save()
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


class ArticleDetailView(DetailView, FormMixin):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'
    form_class = CommentCreationForm


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/update.html'

    def get_success_url(self):  # self.object는 target_object와 동일하다고 보면 됨
        obj = Article.objects.get(pk=self.object.id)

        session = requests.Session()
        payload = {'lyrics': obj.content}
        session = requests.Session()
        res = session.post(URL, headers=headers, data=payload)
        result = json.loads(res.text)['emotion_score']
        session.close()

        result_dict = {'joy': result[0], 'sadness': result[1], 'fear': result[2], 'upset': result[3],
                       'anger': result[4], 'hurt': result[5]}

        obj.joy = result_dict['joy']
        obj.sadness = result_dict['sadness']
        obj.fear = result_dict['fear']
        obj.upset = result_dict['upset']
        obj.anger = result_dict['anger']
        obj.hurt = result_dict['hurt']

        obj.save()
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'


class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 20

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}

{% block content %}


    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>
                Delete Article : {{ target_article.title }}
            </h4>
        </div>
        <div>
            <form action="{% url 'articleapp:delete' pk=target_article.pk %}"
                  method="post">
                {% csrf_token %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-danger rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}
<style>
    .map_wrap, .map_wrap * {margin:0;padding:0;font-family:'Malgun Gothic',dotum,'돋움',sans-serif;font-size:12px;}
    .map_wrap a, .map_wrap a:hover, .map_wrap a:active{color:#000;text-decoration: none;}
    .map_wrap {position:relative;width:100%;height:500px;}
    #menu_wrap {position:absolute;top:0;left:0;bottom:0;width:250px;margin:10px 0 30px 10px;padding:5px;overflow-y:auto;background:rgba(255, 255, 255, 0.7);z-index: 1;font-size:12px;border-radius: 10px;}
    .bg_white {background:#fff;}
    #menu_wrap hr {display: block; height: 1px;border: 0; border-top: 2px solid #5F5F5F;margin:3px 0;}
    #menu_wrap .option{text-align: center;}
    #menu_wrap .option p {margin:10px 0;}
    #menu_wrap .option button {margin-left:5px;}
    #placesList li {list-style: none;}
    #placesList .item {position:relative;border-bottom:1px solid #888;overflow: hidden;cursor: pointer;min-height: 65px;}
    #placesList .item span {display: block;margin-top:4px;}
    #placesList .item h5, #placesList .item .info {text-overflow: ellipsis;overflow: hidden;white-space: nowrap;}
    #placesList .item .info{padding:10px 0 10px 55px;}
    #placesList .info .gray {color:#8a8a8a;}
    #placesList .info .jibun {padding-left:26px;background:url(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/places_jibun.png) no-repeat;}
    #placesList .info .tel {color:#009900;}
    #placesList .item .markerbg {float:left;position:absolute;width:36px; height:37px;margin:10px 0 0 10px;background:url(https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png) no-repeat;}
    #placesList .item .marker_1 {background-position: 0 -10px;}
    #placesList .item .marker_2 {background-position: 0 -56px;}
    #placesList .item .marker_3 {background-position: 0 -102px}
    #placesList .item .marker_4 {background-position: 0 -148px;}
    #placesList .item .marker_5 {background-position: 0 -194px;}
    #placesList .item .marker_6 {background-position: 0 -240px;}
    #placesList .item .marker_7 {background-position: 0 -286px;}
    #placesList .item .marker_8 {background-position: 0 -332px;}
    #placesList .item .marker_9 {background-position: 0 -378px;}
    #placesList .item .marker_10 {background-position: 0 -423px;}
    #placesList .item .marker_11 {background-position: 0 -470px;}
    #placesList .item .marker_12 {background-position: 0 -516px;}
    #placesList .item .marker_13 {background-position: 0 -562px;}
    #placesList .item .marker_14 {background-position: 0 -608px;}
    #placesList .item .marker_15 {background-position: 0 -654px;}
    #pagination {margin:10px auto;text-align: center;}
    #pagination a {display:inline-block;margin-right:10px;}
    #pagination .on {font-weight: bold; cursor: default;color:#777;}
</style>
{% block content %}
    <div class="container text-center" style="padding-top: 8px">
        <div class="my-2 mx-4">
            {#      제목, 장소, 글쓴이, 작성일자      #}
            <a class="NNS_B" href="https://www.youtube.com/results?search_query={{ target_article.title }} 음악" target="_blank">{{ target_article.title }}</a>
        <div class="my-4" style="display: inline">
                <a href="{% url 'likeapp:article_like' article_pk=target_article.pk %}" class="material-icons"
                style="vertical-align: middle; font-size:1.4rem; color: #f88;">
                    favorite
                </a>
                <span style="vertical-align: middle; font-size:1.1rem;">
                    {{ target_article.like }}
                </span>
             </div>
            {% if target_article.is_private == True %}
                <span class="material-icons" style="display: inline; position: relative; top: 0.5rem;">
                    lock
                </span>
            {% endif %}
            {# Like App : 좋아요 기능 이식 END #}
            <h3>{{ target_article.writer.profile.nickname }}</h3>
            <p>{{ target_article.created_at }}</p>
            <div>
                <div>
                    {# joy, sadness, fear, upset, anger, hurt #}
                    {#  # 기쁨, 슬픔, 불안, 당항, 분노, 상처#}
                    <p style="margin: 0.2rem; display: inline;">기쁨 : {{ target_article.joy }}</p>
                    <p style="margin: 0.2rem; display: inline;">슬픔 : {{ target_article.sadness }}</p>
                    <p style="margin: 0.2rem; display: inline;">불안 : {{ target_article.fear }}</p>
                </div>
                <div>
                    <p style="margin: 0.2rem; display: inline;">당항 : {{ target_article.upset }}</p>
                    <p style="margin: 0.2rem; display: inline;">분노 : {{ target_article.anger }}</p>
                    <p style="margin: 0.2rem; display: inline;">상처 : {{ target_article.hurt }}</p>
                </div>
            </div>
        </div>

        <h3 class="NNS_B">{{ target_article.place }}</h3>
        <div id="map" style="width:100%;height:450px; transform: scale(0.9,0.9);"></div>
        <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=7a0506c93dc9967fe1cbf31894fab580&libraries=services"></script>
        <script>
        var mapContainer = document.getElementById('map'), // 지도를 표시할 div
            mapOption = {
                center: new kakao.maps.LatLng({{ target_article.lat }}, {{ target_article.lon }}), // 지도의 중심좌표
                level: 3 // 지도의 확대 레벨
            };

        // 지도를 생성합니다
        var map = new kakao.maps.Map(mapContainer, mapOption);

        // 주소-좌표 변환 객체를 생성합니다
        var geocoder = new kakao.maps.services.Geocoder();
        map.setCenter(new kakao.maps.LatLng({{ target_article.lat }}, {{ target_article.lon }}));

        var mapContainer = document.getElementById('map'), // 지도를 표시할 div
            mapOption = {
                center: new kakao.maps.LatLng({{ target_article.lat }}, {{ target_article.lon }}), // 지도의 중심좌표
                level: 5 // 지도의 확대 레벨
            };

        // 지도를 클릭한 위치에 표출할 마커입니다
        var marker = new kakao.maps.Marker({
            // 지도 중심좌표에 마커를 생성합니다
            position: map.getCenter()
        });
        // 지도에 마커를 표시합니다
        marker.setMap(map);


        </script>
        <hr>

        <div class="my-4">
            {#      게시글 대표 이미지, 게시글 내용      #}
            <img src="{{ target_article.image.url }}"
                 class="article_image"
                 alt="">
            <div class="article_content my-5">
                {{ target_article.content | safe}}
                {#  html 태그들을 안전하게 반영시켜주는 역할을 함 : safe #}
            </div>
            {% if target_article.writer == user %}
            <div>
                <a href="{% url 'articleapp:update' pk=target_article.pk %}"
                   class="btn btn-success rounded-pill px-5">
                    Update
                </a>
                <a href="{% url 'articleapp:delete' pk=target_article.pk %}"
                   class="btn btn-danger rounded-pill px-5">
                    Delete
                </a>
            </div>
            {% endif %}
        </div>

        <hr>

        <div class="text-center my-4">
            {#      댓글 내용, 댓글 작성      #}
            {% for comment in target_article.comment.all %}
                <div class="comment_box">

                    <div>
                        <span style="font-size: 1.4rem;"
                        class="NNS_B">
                            {{ comment.writer.profile.nickname }}
                        </span>{# writer는 객체 그 자체이다. #}
                        <span>{{ comment.created_at }}</span>
                    </div>
                    <div>
                        <p>
                            {{ comment.content }}

                        </p>
                    </div>
                {% if comment.writer == user %}
                    <div style="text-align: right">
                        <a href="{% url 'commentapp:delete' pk=comment.pk %}"
                        class="btn btn-danger rounded-pill px-5">Delete</a>
                    </div>
                {% endif %}
                </div>
            {% endfor %}

            {% include 'commentapp/create.html' %}

        </div>
    </div>


{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>

        .container{
            padding: 0;
            margin: 0 auto;
        }

        .container div {
            width: 8rem;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 2rem;
            flex-direction: column;
            box-shadow: 0 0 .5rem darkgray;
        }

        .container img {
            width: 100%;
            border-radius: 2rem;
        }

    </style>

    <div class="container">

        {% for article in article_list %}
            {% if article.is_private == False %}
            <div class="tmp" style="margin: 1.3rem">
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img src="{{ article.image.url }}" alt="" class="article_list_contain_size" style="size:auto;">
                </a>
                <span class="NNS_B">{{ article.title|truncatechars:8 }}</span>
            </div>
            {% endif %}
        {% endfor %}

    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>

    {% include 'snippets/pagination.html' %}

    <div class="text-center">
        <a href="{% url 'articleapp:create' %}"
           class="btn btn-outline-dark rounded-pill px-5 my-3">
            Create Article
        </a>
    </div>




{% endblock %}